name: Update this repo's README

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: deepaksingh1984/deepaksingh1984@v1
        with:
          feed-url: https://techmesh.tech/feed/
          readme-section: blog
          branch: main
